version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: nac_postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # EKLENEN SATIR
    networks:
      - nac_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: nac_redis
    restart: unless-stopped
    networks:
      - nac_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: nac_api
    restart: unless-stopped
    # İleride API kodlarımızı yazacağımız klasörü build edeceğiz
    build: 
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - nac_net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5

  freeradius:
    image: freeradius/freeradius-server:latest-3.2
    container_name: nac_freeradius
    restart: unless-stopped
    command: >
      sh -c "chmod 640 /etc/freeradius/mods-enabled/rest
             chmod 640 /etc/freeradius/sites-enabled/default
             freeradius -X"
    ports:
      - "1812:1812/udp" # Authentication [cite: 25]
      - "1813:1813/udp" # Accounting [cite: 25]
    volumes:
      - ./radius/rest:/etc/raddb/mods-enabled/rest
      - ./radius/default:/etc/raddb/sites-enabled/default
    networks:
      - nac_net
    depends_on:
      api:
        condition: service_healthy

networks:
  nac_net:
    driver: bridge

volumes:
  pg_data: